name: Daily Check
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install core deps (no Flask in CI)
        run: python -m pip install -r requirements-core.txt
        # Eğer kurumsal proxy gerekiyorsa aşağıdaki env’i aç (Secrets'lara koy):
        # env:
        #   HTTP_PROXY: ${{ secrets.HTTP_PROXY }}
        #   HTTPS_PROXY: ${{ secrets.HTTPS_PROXY }}
        #   NO_PROXY: "127.0.0.1,localhost"
        #   PIP_INDEX_URL: ${{ secrets.PIP_INDEX_URL }}  # örn: https://pypi.org/simple
        #   PIP_TRUSTED_HOST: pypi.org files.pythonhosted.org
      - name: Run checker
        env:
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
          MAILGUN_KEY: ${{ secrets.MAILGUN_KEY }}
        run: python check.py
      - name: Commit updates
        run: |
          git config user.name "deadline-bot"
          git config user.email "bot@example.com"
          git add links.csv changes.csv || true
          git commit -m "daily update [skip ci]" || echo "no changes"
          git pull --rebase origin "${GITHUB_REF_NAME}"
          git push
